# Análise de desempenho: Serial vs. Paralelo

Nesta etapa, será utilizado o arquivo **`comparacao_geral.csv`** para gerar as seguintes análises:

- tabela consolidada com os tempos de execução;
- tabela pivô por tamanho da entrada e método utilizado;
- gráfico de tempo de execução;
- gráfico de speedup;
- gráfico de eficiência.

In [4]:
%pip install plotly
import pandas as pd
import plotly.express as px
from pathlib import Path

candidatos = [
    Path("comparacao_serial_parallel/comparacao_geral.csv"),
    Path("serial_parallel_processing_refatorado/comparacao_serial_parallel/comparacao_geral.csv"),
    Path("/mnt/data/serial_parallel_processing_refatorado/comparacao_serial_parallel/comparacao_geral.csv"),
    Path("comparacao_geral.csv"),
]

csv_path = next((p for p in candidatos if p.exists()), None)

if csv_path is None:
    raise FileNotFoundError(
        "Não encontrei o arquivo 'comparacao_geral.csv'. "
        "Verifique se ele está dentro da pasta 'comparacao_serial_parallel'."
    )

print(f"Arquivo encontrado: {csv_path}")

df = pd.read_csv(csv_path)
df

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting plotly
  Downloading plotly-6.7.0-py3-none-any.whl.metadata (8.6 kB)
Collecting narwhals>=1.15.1 (from plotly)
  Downloading narwhals-2.19.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: packaging in c:\users\finan\appdata\roaming\python\python313\site-packages (from plotly) (25.0)
Downloading plotly-6.7.0-py3-none-any.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.9 MB 8.8 MB/s eta 0:00:02
   -------------------------------- ------- 8.1/9.9 MB 28.9 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 26.4 MB/s  0:00:00
Downloading narwhals-2.19.0-py3-none-any.whl (446 kB)
Installing collected packages: narwhals, plotly

   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   ---------------------------------------- 2/2 [plotly]

Successfully installed narwhals-2.19.0 plotly-6.7.0
Note: you may need to restart the kernel to use updated packages.
Arquivo encontrado: comparacao_serial_parallel\comparacao_geral.csv

,metodo,n,m,p,tempo_segundos,speedup,eficiencia,processos,valido,observacao
0,Serial,10,20,10,0.000204,1.000000,1.000000,1,True,Baseline sequencial
1,Paralelo sem agrupamento,10,20,10,0.243951,0.000838,0.000209,4,True,Uma tarefa por célula (100 tarefas)
2,Paralelo por linha,10,20,10,0.210412,0.000971,0.000243,4,True,Uma tarefa por linha (10 tarefas)
3,Paralelo por blocos,10,20,10,0.214763,0.000952,0.000238,4,True,Blocos de 20 linhas
4,Serial,60,120,60,0.050253,1.000000,1.000000,1,True,Baseline sequencial
5,Paralelo sem agrupamento,60,120,60,0.276610,0.181673,0.045418,4,True,Uma tarefa por célula (3600 tarefas)
6,Paralelo por linha,60,120,60,0.301789,0.166515,0.041629,4,True,Uma tarefa por linha (60 tarefas)
7,Paralelo por blocos,60,120,60,0.229900,0.218584,0.054646,4,True,Blocos de 20 linhas
8,Serial,120,240,120,0.268687,1.000000,1.000000,1,True,Baseline sequencial
9,Paralelo sem agrupamento,120,240,120,0.486681,0.552080,0.138020,4,True,Uma tarefa por célula (14400 tarefas)
10,Paralelo por linha,120,240,120,0.485644,0.553260,0.138315,4,True,Uma tarefa por linha (120 tarefas)
11,Paralelo por blocos,120,240,120,0.334894,0.802305,0.200576,4,True,Blocos de 20 linhas

In [5]:

# Ajustes auxiliares para visualização
df["tamanho"] = df["n"].astype(str) + " x " + df["m"].astype(str)
ordem_metodos = [
    "Serial",
    "Paralelo sem agrupamento",
    "Paralelo por linha",
    "Paralelo por blocos",
]
df["metodo"] = pd.Categorical(df["metodo"], categories=ordem_metodos, ordered=True)
df = df.sort_values(["n", "metodo"]).reset_index(drop=True)

df

,metodo,n,m,p,tempo_segundos,speedup,eficiencia,processos,valido,observacao,tamanho
0,Serial,10,20,10,0.000204,1.000000,1.000000,1,True,Baseline sequencial,10 x 20
1,Paralelo sem agrupamento,10,20,10,0.243951,0.000838,0.000209,4,True,Uma tarefa por célula (100 tarefas),10 x 20
2,Paralelo por linha,10,20,10,0.210412,0.000971,0.000243,4,True,Uma tarefa por linha (10 tarefas),10 x 20
3,Paralelo por blocos,10,20,10,0.214763,0.000952,0.000238,4,True,Blocos de 20 linhas,10 x 20
4,Serial,60,120,60,0.050253,1.000000,1.000000,1,True,Baseline sequencial,60 x 120
5,Paralelo sem agrupamento,60,120,60,0.276610,0.181673,0.045418,4,True,Uma tarefa por célula (3600 tarefas),60 x 120
6,Paralelo por linha,60,120,60,0.301789,0.166515,0.041629,4,True,Uma tarefa por linha (60 tarefas),60 x 120
7,Paralelo por blocos,60,120,60,0.229900,0.218584,0.054646,4,True,Blocos de 20 linhas,60 x 120
8,Serial,120,240,120,0.268687,1.000000,1.000000,1,True,Baseline sequencial,120 x 240
9,Paralelo sem agrupamento,120,240,120,0.486681,0.552080,0.138020,4,True,Uma tarefa por célula (14400 tarefas),120 x 240
10,Paralelo por linha,120,240,120,0.485644,0.553260,0.138315,4,True,Uma tarefa por linha (120 tarefas),120 x 240
11,Paralelo por blocos,120,240,120,0.334894,0.802305,0.200576,4,True,Blocos de 20 linhas,120 x 240

In [6]:

# Tabela pivô com os tempos lado a lado
tabela_tempos = (
    df.pivot(index="tamanho", columns="metodo", values="tempo_segundos")
      .reset_index()
)

tabela_tempos

metodo,tamanho,Serial,Paralelo sem agrupamento,Paralelo por linha,Paralelo por blocos
0,10 x 20,0.000204,0.243951,0.210412,0.214763
1,120 x 240,0.268687,0.486681,0.485644,0.334894
2,60 x 120,0.050253,0.276610,0.301789,0.229900

In [7]:

# Tabela resumida com speedup e eficiência apenas dos métodos paralelos
tabela_metricas = (
    df[df["metodo"] != "Serial"]
    [["tamanho", "metodo", "tempo_segundos", "speedup", "eficiencia", "processos", "valido", "observacao"]]
    .reset_index(drop=True)
)

tabela_metricas

,tamanho,metodo,tempo_segundos,speedup,eficiencia,processos,valido,observacao
0,10 x 20,Paralelo sem agrupamento,0.243951,0.000838,0.000209,4,True,Uma tarefa por célula (100 tarefas)
1,10 x 20,Paralelo por linha,0.210412,0.000971,0.000243,4,True,Uma tarefa por linha (10 tarefas)
2,10 x 20,Paralelo por blocos,0.214763,0.000952,0.000238,4,True,Blocos de 20 linhas
3,60 x 120,Paralelo sem agrupamento,0.276610,0.181673,0.045418,4,True,Uma tarefa por célula (3600 tarefas)
4,60 x 120,Paralelo por linha,0.301789,0.166515,0.041629,4,True,Uma tarefa por linha (60 tarefas)
5,60 x 120,Paralelo por blocos,0.229900,0.218584,0.054646,4,True,Blocos de 20 linhas
6,120 x 240,Paralelo sem agrupamento,0.486681,0.552080,0.138020,4,True,Uma tarefa por célula (14400 tarefas)
7,120 x 240,Paralelo por linha,0.485644,0.553260,0.138315,4,True,Uma tarefa por linha (120 tarefas)
8,120 x 240,Paralelo por blocos,0.334894,0.802305,0.200576,4,True,Blocos de 20 linhas

In [10]:
%pip install -U nbformat ipykernel plotly

Requirement already satisfied: nbformat in c:\users\finan\appdata\local\programs\python\python313\lib\site-packages (5.10.4)
Requirement already satisfied: ipykernel in c:\users\finan\appdata\local\programs\python\python313\lib\site-packages (7.2.0)
Requirement already satisfied: plotly in c:\users\finan\appdata\local\programs\python\python313\lib\site-packages (6.7.0)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\finan\appdata\local\programs\python\python313\lib\site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\finan\appdata\local\programs\python\python313\lib\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\finan\appdata\roaming\python\python313\site-packages (from nbformat) (5.8.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\finan\appdata\roaming\python\python313\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: comm>=0.1.1 in c:\users\finan\appdata\roaming\python\python313\site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\finan\appdata\roaming\python\python313\site-packages (from ipykernel) (1.8.16)
Requirement already satisfied: ipython>=7.23.1 in c:\users\finan\appdata\roaming\python\python313\site-packages (from ipykernel) (9.4.0)
Requirement already satisfied: jupyter-client>=8.8.0 in c:\users\finan\appdata\local\programs\python\python313\lib\site-packages (from ipykernel) (8.8.0)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\finan\appdata\roaming\python\python313\site-packages (from ipykernel) (0.1.7)
Requirement already satisfied: nest-asyncio>=1.4 in c:\users\finan\appdata\roaming\python\python313\site-packages (from ipykernel) (1.6.0)
Requirement already satisfied: packaging>=22 in c:\users\finan\appdata\roaming\python\python313\site-packages (from ipykernel) (25.0)
Requirement already satisfied: psutil>=5.7 in c:\users\finan\appdata\roaming\python\python313\site-packages (from ipykernel) (7.0.0)
Requirement already satisfied: pyzmq>=25 in c:\users\finan\appdata\roaming\python\python313\site-packages (from ipykernel) (27.0.1)
Requirement already satisfied: tornado>=6.4.1 in c:\users\finan\appdata\roaming\python\python313\site-packages (from ipykernel) (6.5.2)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\finan\appdata\local\programs\python\python313\lib\site-packages (from plotly) (2.19.0)
Requirement already satisfied: colorama in c:\users\finan\appdata\local\programs\python\python313\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.4.6)
Requirement already satisfied: decorator in c:\users\finan\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in c:\users\finan\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (1.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\finan\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (0.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\finan\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (3.0.51)
Requirement already satisfied: pygments>=2.4.0 in c:\users\finan\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (2.19.2)
Requirement already satisfied: stack_data in c:\users\finan\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: wcwidth in c:\users\finan\appdata\roaming\python\python313\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\finan\appdata\roaming\python\python313\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel) (0.8.4)
Requirement already satisfied: attrs>=22.2.0 in c:\users\finan\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=2.6->nbformat) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\finan\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\finan\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\finan\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\finan\appdata\roaming\python\python313\site-packages (from jupyter-client>=8.8.0->ipykernel) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\finan\appdata\roaming\python\python313\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.3.8)
Requirement already satisfied: pywin32>=300 in c:\users\finan\appdata\roaming\python\python313\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (311)
Requirement already satisfied: six>=1.5 in c:\users\finan\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->jupyter-client>=8.8.0->ipykernel) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\finan\appdata\roaming\python\python313\site-packages (from stack_data->ipython>=7.23.1->ipykernel) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\finan\appdata\roaming\python\python313\site-packages (from stack_data->ipython>=7.23.1->ipykernel) (3.0.0)
Requirement already satisfied: pure-eval in c:\users\finan\appdata\roaming\python\python313\site-packages (from stack_data->ipython>=7.23.1->ipykernel) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [17]:
import plotly.express as px
import plotly.io as pio

pio.renderers.default = "browser"

fig_tempo = px.line(
    df,
    x="tamanho",
    y="tempo_segundos",
    color="metodo",
    markers=True,
    title="Tempo de execução por tamanho e método"
)

fig_tempo.update_layout(
    xaxis_title="Tamanho da matriz",
    yaxis_title="Tempo de execução (s)"
)

fig_tempo.show()

In [14]:
import plotly.express as px
import plotly.io as pio

pio.renderers.default = "browser"

fig_tempo = px.line(
    df,
    x="tamanho",
    y="tempo_segundos",
    color="metodo",
    markers=True,
    title="Tempo de execução por tamanho e método"
)

fig_tempo.update_layout(
    xaxis_title="Tamanho da matriz",
    yaxis_title="Tempo de execução (s)"
)

fig_tempo.show()

In [15]:

fig_eficiencia = px.bar(
    df_speedup,
    x="tamanho",
    y="eficiencia",
    color="metodo",
    barmode="group",
    text_auto=".2f",
    title="Eficiência dos métodos paralelos",
    labels={
        "tamanho": "Tamanho da matriz",
        "eficiencia": "Eficiência",
        "metodo": "Método"
    }
)

fig_eficiencia.update_layout(xaxis_title="Tamanho da matriz", yaxis_title="Eficiência")
fig_eficiencia.show()

In [16]:

# Melhor método por tamanho de entrada
melhores = (
    df.loc[df.groupby("tamanho")["tempo_segundos"].idxmin(), ["tamanho", "metodo", "tempo_segundos"]]
    .reset_index(drop=True)
    .rename(columns={"metodo": "melhor_metodo", "tempo_segundos": "melhor_tempo"})
)

melhores

     tamanho melhor_metodo  melhor_tempo
0    10 x 20        Serial      0.000204
1  120 x 240        Serial      0.268687
2   60 x 120        Serial      0.050253

## Interpretação esperada

- **Serial** serve como baseline.
- **Paralelo sem agrupamento** tende a sofrer mais com overhead.
- **Paralelo por linha** reduz parte desse overhead.
- **Paralelo por blocos** tende a ser a estratégia mais equilibrada, pois diminui o custo de criação e coordenação das tarefas.

Use os gráficos e tabelas acima para colocar no slide:
1. uma tabela de tempos;
2. um gráfico de tempo;
3. um gráfico de speedup.